version: '3'
services:
  mongo:
    image: mongo:3.6
  app:
    volumes:
     - .:/app
     - /app/node_modules
    build: .
    ports:
     - "3001:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/paredao 
    links:
     - mongo 
    depends_on: 
     - mongo 

     