FROM node:8-slim AS node-app

WORKDIR /app

COPY package.json /app/package.json

RUN npm install

COPY . /app

RUN npm run build

FROM nginx:1.15.2-alpine as nginx-app

COPY --from=node-app /app/dist /var/www

COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]