FROM node:8-slim AS node-app

WORKDIR /app
ENV NODE_ENV production

COPY package.json /app/package.json

RUN npm i -g nodemon
RUN npm install

COPY . /app

CMD ["npm","run", "build"]

FROM nginx:1.15.2-alpine as nginx-app

COPY --from=node-app /app/dist /var/www

COPY nginx.conf /etc/nginx/nginx.conf
