version: '3'
services:
  mongo:
    image: mongo:3.6
  app:
    volumes:
     - .:/app
     - /node_modules
    build: .
    ports:
     - "8080:3001"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/app 
     - PORT=3001
     - ENV=development
     - SESSION_SECRET=bbb2018
    links:
     - mongo 
    depends_on: 
     - mongo 

     